### ISSUE TITLE
Package Commentary

### ISSUE THREAD

**Issue by simeonwillbanks** [technoweenie/grohl#7]
Hi @technoweenie and @alindeman!

I'm a new Gopher, and I'd like to help.  May I add some [package commentary](http://golang.org/doc/effective_go.html#commentary)?   Writing comments will familiarize myself with Grohl, and hopefully, learn more about Go.
1. Package Comment
   - _"Every package should have a package comment, a block comment preceding the package clause."_
2. Doc Comments
   - _"Inside a package, any comment immediately preceding a top-level declaration serves as a doc comment for that declaration. Every exported (capitalized) name in a program should have a doc comment."_
3. Generate documentation with [godoc](http://golang.org/cmd/godoc/)
   - `$ godoc grohl | grep Statter`

Thoughts?

Thanks,
Simeon

**Comment by technoweenie** [comment]
I was planning on doing that once I was ready to push for a real release. The README was ripped from [asenchi/scrolls](/asenchi/scrolls), and isn't even correct.  It simply served as a guide when I started work on this.

I don't mind, but this library is still in flux.  I just wanted to give a bit more context on why it is like it is :)

**Comment by simeonwillbanks** [comment]
Very cool, makes sense, and thanks!

Since the library is in flux, I'll fork but keep Pull Requests to a minimum.  While development continues, I can merge upstream changes and update comments. I don't want to get in the way!  Thoughts?

**Comment by technoweenie** [comment]
Go for it!

**Comment by simeonwillbanks** [comment]
Sweet! :smile:
